services:
  roman-numbers-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8080:8080"
    container_name: roman-numbers-api

  roman-numbers-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: tests
    container_name: roman-numbers-tests